#!/bin/sh

command_exists () {
    type "$1" &> /dev/null ;
}

if command_exists bazelisk; then
    bazelisk test --define version="local" //...:all
else
    bazel test --define version="local" //...:all
fi

